language: ruby
rvm:
- 2.2.5
install:
- gem install sass --version 3.4.22
- gem install jekyll --version 2.5.3
- gem install jekyll-watch -v 2.0.0
- gem install jekyll-compass
- gem install compass --version 0.12.5
- gem install kramdown -v 1.17.0
- gem install link-checker
- gem install jekyll-postfiles
- gem install jekyll-sitemap
# - gem install html-proofer
script:
- jekyll build
- compass compile
# - htmlproof ./_site
after_success:
# - s3_website push
- check-links 'http://web.stevens.edu/cognition'
env:
  on:
    branch: master
